### ISSUE TITLE
Camera not muting

### ISSUE THREAD

**Issue by jjshoe** [jjshoe/MuteDefaults#1]
I noticed today that the camera is no longer getting muted. This most likely is due to a change in the element id of the camera icon. I will try to get a fix out for it tonight.

**Comment by asharpe-squiz** [comment]
This is working for me in a 1-1 on my work account, which appears to be using a different UI my personal account.

**Comment by abstratt** [comment]
@jjshoe Yeah, there are no element ids anymore. The only identifiable piece of information seems to be the aria labels. 

I tried this on the console and it worked fine on Chrome:

Mute:
```
document.querySelectorAll('[aria-label="Mute video camera"]')[0].dispatchEvent(new MouseEvent("click", {
    "view": window,
    "bubbles": true,
    "cancelable": false
}));
```

Unmute:
```
document.querySelectorAll('[aria-label="Unmute video camera"]')[0].dispatchEvent(new MouseEvent("click", {
    "view": window,
    "bubbles": true,
    "cancelable": false
}));
```

**Comment by abstratt** [comment]
On IE (also still works on Chrome, but it is deprecated and not in the standard), the event creation code is a bit different:

```
var event = document.createEvent("MouseEvent");
event.initEvent("click", true, false);
document.querySelectorAll('[aria-label="Mute video camera"]')[0].dispatchEvent(event);
```

See: https://stackoverflow.com/questions/27176983/dispatchevent-not-working-in-ie11

**Comment by jjshoe** [comment]
@abstratt are you on hangouts or meet?

**Comment by abstratt** [comment]
@jjshoe Sorry, that was on Hangouts. On Meet, the strategy for finding the right element may require a different selector (maybe the ones you have in place still works).

**Comment by abstratt** [comment]
@jjshoe BTW, no reason to use querySelectorAll(), querySelector() (which is already in use to support Meet) would be best.

**Comment by jjshoe** [comment]
https://hangouts.google.com/ - Is still actively working for me, both my mic and camera mute. I'll have to investigate some more.

**Comment by abstratt** [comment]
I saw this on 1-to-1 call.

**Comment by jjshoe** [comment]
@abstratt - If you load an unpacked extension, using master as the source, you can help beta test. If you're not comfortable doing this, I expect to release in a week. This new version will try to keep clicking, no more once and done.

**Comment by jjshoe** [comment]
A version has been published to the chrome store that should solve this issue. Please open a new issue if you experience any problems with 2.0.
