### ISSUE TITLE
Read this first

### ISSUE THREAD

**Issue by jjshoe** [jjshoe/MuteDefaults#12]
I no longer actively work in an environment that uses either google hangouts or google meet.

If you're opening an issue, please include the URL of the page the extension doesn't work for you on. This is the only way I can attempt to help you at this point.

**Comment by drogers100** [comment]
Is it possible to change the code so that when the extension is installed to default settings are already set to mute on and camera off?

**Comment by cheluskis** [comment]
pls checkout https://github.com/cheluskis/hangremote, I'm actively maintaining it so you can make your requests there.
Thanks @jjshoe and AGPL

**Comment by jjshoe** [comment]
Closing out this issue as I've pushed a new version that works solidly with google meet. Also makes use of manifest v3, which the above extension does not.
