### ISSUE TITLE
Hangouts videocalls moved to the new Meet product for G Suite users

### ISSUE THREAD

**Issue by fedeant** [jjshoe/MuteDefaults#2]
Hi, first thanks for your great extension, I use it every day!

In my job we use G Suite (formerly Google Apps) and now when we setup a new video call it is showed in what seems to be a new Google product called Hangouts Meet:
https://gsuite.google.com/learning-center/products/hangouts/get-started-meet/

Unfortunately your extension doesn't work in this new UI.
Could you try to make it work?

I have a personal Google Apps account and if you don't have one to try it I can create a user for you to try.

Let me know and thanks!!

**Comment by oughter** [comment]
#3 adds support for this (I didn't notice this issue when I created the pull request or would have referenced it there).

**Comment by jjshoe** [comment]
I'll review the PR shortly, been swamped in my off hours lately.

**Comment by jjshoe** [comment]
Spent some time working on it tonight. There's a known way to get it to work, but it's a bit hacky. I've found the cause of issues when doing it the right way, but not the solution just yet. Hope to get it figured out in the next couple of days.

**Comment by fedeant** [comment]
Awesome. Thank you very much for looking at it!

**Comment by Shaneob13** [comment]
Hi,

Is there any update on this topic please?

Mute for Camera is working for Hangouts video calls, but not for "Meet" video calls.

Thanks !

**Comment by jjshoe** [comment]
@Shaneob13 - This extension is not designed to work with the Meet interface yet.

**Comment by Shaneob13** [comment]
@jjshoe 
Thanks for the update.
Hopefully this is planned for future development please?

**Comment by jjshoe** [comment]
@fedeant @oughter @Shaneob13 - Meet support is in! If you load an unpacked extension, using master as the source, you can help beta test. If you're not comfortable doing this, I expect to release in a week.

**Comment by fedeant** [comment]
Hi @jjshoe ! Thank you very much!!!
I just installed it and with some quick tests it seems to be working perfectly well (screenshots attached).
I will try it tomorrow in several calls and let you know if I have any issue.
Thanks you very much again!!

![screen shot 2017-09-25 at 9 39 52 pm](https://user-images.githubusercontent.com/11978254/30837387-03b16b3c-a23b-11e7-9b49-e28ef452e45b.png)
![screen shot 2017-09-25 at 9 40 39 pm](https://user-images.githubusercontent.com/11978254/30837388-03b262ee-a23b-11e7-9151-4c62710b9631.png)
![screen shot 2017-09-25 at 9 41 02 pm](https://user-images.githubusercontent.com/11978254/30837389-03b56246-a23b-11e7-81c0-abddacb44953.png)
![screen shot 2017-09-25 at 9 41 29 pm](https://user-images.githubusercontent.com/11978254/30837391-03b72c34-a23b-11e7-9a85-00204c28b421.png)
![screen shot 2017-09-25 at 9 42 12 pm](https://user-images.githubusercontent.com/11978254/30837390-03b63e14-a23b-11e7-8053-1acf92a8aab6.png)

**Comment by jjshoe** [comment]
@fedeant - Thanks for the awesome screenshots! It's been working flawlessly here too. There's only one improvement I could make. That's a total attempts to mute, now that I'm using setInterval, if the selectors ever changed it would try indefinitely. However as the selectors have never changed thus far I'm crossing my fingers for that same luck :)

I'll be using it all day today, and I don't expect to run into any issues. Looking forward to rolling it out to the chrome store shortly!

**Comment by fedeant** [comment]
Haha cool. I already had three calls today and worked perfectly.
Maybe to avoid the selector change issue you can have like a hard limit on the time, or stop checking if the call is started.
If the selector is not found and the call is started, will your code continue checking or will be stopped?

**Comment by jjshoe** [comment]
I'll probably do a total number of attempts. I like the idea of stopping if someone joins the call, but if you open a meeting in a tab five minutes in advance, but don't join it'll attempt to click that entire time.

**Comment by jjshoe** [comment]
A version has been published to the chrome store that should solve this issue. Please open a new issue if you experience any problems with 2.0.
