### ISSUE TITLE
Mute Camera doesn't work

### ISSUE THREAD

**Issue by mdanetzky** [jjshoe/MuteDefaults#4]
I have OSX Sierra, Chrome 58.0.3029.110 (64-bit).
When I start a call from Google Hangouts App the camera isn't muted despite of "Mute the camera automatically" being checked.

**Comment by blackwood** [comment]
Ditto, doesn't change either camera or mic.

**Comment by abstratt** [comment]
Same here, on Linux, Chrome 56.0.2924.87 (64-bit).

**Comment by abstratt** [comment]
Duplicate of #1

**Comment by jjshoe** [comment]
Closing as a duplicate of #1

**Comment by jjshoe** [comment]
@mdanetzky @blackwood support for meets was just added, and rolled out today. Try version 2.0, and see if it works for you, if not, please open a new issue.
