### ISSUE TITLE
Broken in latest version of Meet

### ISSUE THREAD

**Issue by ianhyzy** [jjshoe/MuteDefaults#7]
In the current version of meet, this extension constantly mutes/unmutes the mic/camera, causing the UI to constantly pop in and out.

**Comment by jacobamills** [comment]
Hello from the Google Meet team.

The behavior exhibited by this extension was really bad for users of Google Meet.

A temporary workaround has been added to our codebase to allow this extension to work as-is for the time being. This workaround will be removed in the near future, so please fix your code.

1. You should not be depending on an optimized and obfuscated class name that could change without warning (and, in fact, did).
2. **You need some kind of failure handling** for cases where things don't appear to be working. Retrying every 500 milliseconds for the life of the call is not good.

A `data-is-muted` attribute will shortly be added to the mute control to provide you with something less ephemeral. No guarantee is being made that this attribute will not be changed, altered, or deleted in the future, so again, **please add failure handling**.

**Comment by jjshoe** [comment]
I haven't had a chance to take a look at this, and I'm no longer using hangouts day to day. If anyone wants to toss up a PR I'd be more than happy to review.

@jacobamills do you work at google yourself or have a contact? I'd be more interested in switching back to a mutation observer, and working with them to make that work with the meet product.
