### ISSUE TITLE
Doesn't work with Google Hangouts atm

### ISSUE THREAD

**Issue by tannertaylor2010** [jjshoe/MuteDefaults#9]
When calling someone with hangouts via web browser directly (not using a meet link). Both of our videos were still on by default.

**Comment by jjshoe** [comment]
send me a link to join a meet, and I'd be happy to take a look

**Comment by arkytn** [comment]
Just installed it and turned it on. Doesn't work in Hangout app.

**Comment by jjshoe** [comment]
@arkytn please see comment above yours.
